import { ContactRequest, WebSubscriber } from "../_types/setting.types";

// ─── Contact Requests ─────────────────────────────────────────────────────────
export const MOCK_CONTACT_REQUESTS: ContactRequest[] = [
  {
    id: "cr_1",
    fullName: "James Whitfield",
    email: "james.whitfield@email.com",
    phone: "+1 (555) 203-4411",
    subject: "Issue with my subscription billing",
    message:
      "Hello, I have been charged twice this month for my subscription. I'd like a refund for the duplicate charge. Please look into this as soon as possible. My account ID is #34512.",
    status: "unread",
    createdAt: "2026-04-10T09:32:00Z",
  },
  {
    id: "cr_2",
    fullName: "Sophia Reynolds",
    email: "sophia.r@company.org",
    phone: "+44 20 7946 0801",
    subject: "Partnership Opportunity",
    message:
      "Hi team, I represent a leading logistics company and we'd love to explore a partnership opportunity with Retwho. Could we schedule a call to discuss further?",
    status: "replied",
    createdAt: "2026-04-09T14:15:00Z",
  },
  {
    id: "cr_3",
    fullName: "Ahmed Al-Farsi",
    email: "ahmed.alfarsi@mail.ae",
    phone: "+971 50 123 4567",
    subject: "Account Verification Pending",
    message:
      "I submitted my documents for verification 5 days ago and haven't heard back. My business depends on getting verified. Please expedite or let me know the status.",
    status: "read",
    createdAt: "2026-04-08T11:00:00Z",
  },
  {
    id: "cr_4",
    fullName: "Maria Fernandez",
    email: "maria.f@gmail.com",
    subject: "Feature Request: Bulk Export",
    message:
      "It would be incredibly helpful if we could export all our orders in bulk as a CSV or Excel file. Right now, we have to do it one by one which is very time consuming.",
    status: "read",
    createdAt: "2026-04-07T16:44:00Z",
  },
  {
    id: "cr_5",
    fullName: "Daniel Kim",
    email: "d.kim@techcorp.io",
    phone: "+82 10 9876 5432",
    subject: "API rate limit exceeded",
    message:
      "We are hitting the rate limit on your API frequently. Our integration processes thousands of orders daily. Do you have an enterprise plan with higher limits?",
    status: "replied",
    createdAt: "2026-04-07T08:20:00Z",
  },
  {
    id: "cr_6",
    fullName: "Priya Nair",
    email: "priya.nair@biz.in",
    phone: "+91 98765 43210",
    subject: "Wrong delivery address issue",
    message:
      "One of my orders was delivered to the wrong address even though I entered the correct one during checkout. Order ID: #ORD-20458. Please help resolve this.",
    status: "unread",
    createdAt: "2026-04-06T13:05:00Z",
  },
  {
    id: "cr_7",
    fullName: "Ethan Brooks",
    email: "ethan.brooks@startupzone.com",
    subject: "Request for a Demo",
    message:
      "We are a startup looking to use Retwho for our distribution needs. Could someone from the sales team schedule a product demo for us?",
    status: "archived",
    createdAt: "2026-04-05T10:10:00Z",
  },
  {
    id: "cr_8",
    fullName: "Lin Wei",
    email: "lin.wei@export.cn",
    phone: "+86 138 0013 8000",
    subject: "International shipping availability",
    message:
      "Do you support international shipping to China and Southeast Asia? We are interested in using your platform for cross-border trade.",
    status: "unread",
    createdAt: "2026-04-04T07:30:00Z",
  },
];

// ─── Web Subscribers ──────────────────────────────────────────────────────────
export const MOCK_WEB_SUBSCRIBERS: WebSubscriber[] = [
  {
    id: "sub_1",
    email: "alex.johnson@gmail.com",
    name: "Alex Johnson",
    source: "website",
    status: "active",
    tags: ["wholesaler", "vip"],
    subscribedAt: "2026-04-10T08:00:00Z",
  },
  {
    id: "sub_2",
    email: "nora.smith@company.com",
    name: "Nora Smith",
    source: "blog",
    status: "active",
    tags: ["retailer"],
    subscribedAt: "2026-04-09T11:30:00Z",
  },
  {
    id: "sub_3",
    email: "user123@hotmail.com",
    source: "popup",
    status: "unsubscribed",
    tags: [],
    subscribedAt: "2026-03-28T09:45:00Z",
  },
  {
    id: "sub_4",
    email: "claire.d@biz.fr",
    name: "Claire Dupont",
    source: "footer",
    status: "active",
    tags: ["new-user"],
    subscribedAt: "2026-04-08T14:00:00Z",
  },
  {
    id: "sub_5",
    email: "bounced@invalid.xyz",
    source: "social",
    status: "bounced",
    tags: [],
    subscribedAt: "2026-03-15T06:00:00Z",
  },
  {
    id: "sub_6",
    email: "marco.bianchi@italy.it",
    name: "Marco Bianchi",
    source: "website",
    status: "active",
    tags: ["wholesaler"],
    subscribedAt: "2026-04-07T10:20:00Z",
  },
  {
    id: "sub_7",
    email: "sales.lead@techfirm.io",
    name: "Tech Firm Sales",
    source: "blog",
    status: "active",
    tags: ["b2b", "enterprise"],
    subscribedAt: "2026-04-06T15:55:00Z",
  },
  {
    id: "sub_8",
    email: "random@nowhere.net",
    source: "popup",
    status: "unsubscribed",
    tags: [],
    subscribedAt: "2026-03-01T12:00:00Z",
  },
  {
    id: "sub_9",
    email: "jessica.park@retail.co",
    name: "Jessica Park",
    source: "social",
    status: "active",
    tags: ["retailer", "new-user"],
    subscribedAt: "2026-04-05T08:40:00Z",
  },
  {
    id: "sub_10",
    email: "old.address@email.com",
    name: "Old User",
    source: "footer",
    status: "bounced",
    tags: ["inactive"],
    subscribedAt: "2026-01-10T07:00:00Z",
  },
  {
    id: "sub_11",
    email: "fatima.ali@market.sa",
    name: "Fatima Ali",
    source: "website",
    status: "active",
    tags: ["wholesaler", "vip"],
    subscribedAt: "2026-04-03T09:15:00Z",
  },
  {
    id: "sub_12",
    email: "george.m@logistics.eu",
    name: "George M.",
    source: "blog",
    status: "active",
    tags: ["b2b"],
    subscribedAt: "2026-04-02T13:00:00Z",
  },
];
