import { Shop } from "../_types/store.types";

const now = new Date().toISOString();

export const MOCK_STORES: Shop[] = [
  // ==========================================
  // ACTIVE WHOLESALERS (8 items)
  // ==========================================
  {
    id: "w1",
    createdBy: "u1",
    type: "wholesaler",
    companyName: "Global Wholesale Inc.",
    dbaName: "Global Market",
    accountId: "ACC-W001",
    phone: "(800) 555-0101",
    email: "contact@globalwholesale.com",
    fein: "12-3456789",
    resaleNumber: "RN-9876543",
    tobaccoLicense: "TL-5544332",
    idNumber: "ID-111222",
    address: {
      street: "100 Industry Blvd",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90001",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "w2",
    createdBy: "u2",
    type: "wholesaler",
    companyName: "Prime Distributors LLC",
    dbaName: "Prime Distribution",
    accountId: "ACC-W002",
    phone: "(800) 555-0102",
    email: "hello@primedistributors.com",
    fein: "21-3456780",
    resaleNumber: "RN-9876544",
    tobaccoLicense: "TL-5544333",
    idNumber: "ID-111223",
    address: {
      street: "150 Commerce Way",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "w3",
    createdBy: "u3",
    type: "wholesaler",
    companyName: "National Supply Network",
    dbaName: "NSN Supplies",
    accountId: "ACC-W003",
    phone: "(800) 555-0103",
    email: "sales@nsn.com",
    fein: "31-3456781",
    resaleNumber: "RN-9876545",
    tobaccoLicense: "TL-5544334",
    idNumber: "ID-111224",
    address: {
      street: "200 Supply Chain Dr",
      city: "Dallas",
      state: "TX",
      zipCode: "75201",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "w4",
    createdBy: "u4",
    type: "wholesaler",
    companyName: "Atlantic Wholesale",
    dbaName: "Atlantic Market",
    accountId: "ACC-W004",
    phone: "(800) 555-0104",
    email: "info@atlanticwholesale.com",
    fein: "41-3456782",
    resaleNumber: "RN-9876546",
    tobaccoLicense: "TL-5544335",
    idNumber: "ID-111225",
    address: {
      street: "300 Ocean Ave",
      city: "Miami",
      state: "FL",
      zipCode: "33101",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "w5",
    createdBy: "u5",
    type: "wholesaler",
    companyName: "Midwest Merchants Inc",
    dbaName: "Midwest Goods",
    accountId: "ACC-W005",
    phone: "(800) 555-0105",
    email: "vendor@midwestmerchants.com",
    fein: "51-3456783",
    resaleNumber: "RN-9876547",
    tobaccoLicense: "TL-5544336",
    idNumber: "ID-111226",
    address: {
      street: "400 Prairie St",
      city: "Omaha",
      state: "NE",
      zipCode: "68102",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "w6",
    createdBy: "u6",
    type: "wholesaler",
    companyName: "Pacific Trade Co",
    dbaName: "PacTrade",
    accountId: "ACC-W006",
    phone: "(800) 555-0106",
    email: "support@pactrade.com",
    fein: "61-3456784",
    resaleNumber: "RN-9876548",
    tobaccoLicense: "TL-5544337",
    idNumber: "ID-111227",
    address: {
      street: "500 Trade Port Rd",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "w7",
    createdBy: "u7",
    type: "wholesaler",
    companyName: "Continental Goods LLC",
    dbaName: "Continental",
    accountId: "ACC-W007",
    phone: "(800) 555-0107",
    email: "contact@continentalgoods.com",
    fein: "71-3456785",
    resaleNumber: "RN-9876549",
    tobaccoLicense: "TL-5544338",
    idNumber: "ID-111228",
    address: {
      street: "600 Center Blvd",
      city: "Denver",
      state: "CO",
      zipCode: "80202",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "w8",
    createdBy: "u8",
    type: "wholesaler",
    companyName: "Eastern Seaboard Supply",
    dbaName: "ESS Distribution",
    accountId: "ACC-W008",
    phone: "(800) 555-0108",
    email: "sales@ess.com",
    fein: "81-3456786",
    resaleNumber: "RN-9876550",
    tobaccoLicense: "TL-5544339",
    idNumber: "ID-111229",
    address: {
      street: "700 Harbor Way",
      city: "Boston",
      state: "MA",
      zipCode: "02108",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },

  // ==========================================
  // ACTIVE RETAILERS (8 items)
  // ==========================================
  {
    id: "r1",
    createdBy: "u9",
    type: "retailer",
    companyName: "City Retail LLC",
    dbaName: "City Mart",
    accountId: "ACC-R001",
    phone: "(800) 555-0201",
    email: "info@cityretail.com",
    fein: "98-7654321",
    resaleNumber: "RN-1234567",
    tobaccoLicense: "TL-1122334",
    idNumber: "ID-333444",
    address: {
      street: "200 Main St",
      city: "San Francisco",
      state: "CA",
      zipCode: "94105",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "r2",
    createdBy: "u10",
    type: "retailer",
    companyName: "Corner Shop Partners",
    dbaName: "Corner Deli",
    accountId: "ACC-R002",
    phone: "(800) 555-0202",
    email: "hello@cornerdeli.com",
    fein: "97-7654322",
    resaleNumber: "RN-1234568",
    tobaccoLicense: "TL-1122335",
    idNumber: "ID-333445",
    address: {
      street: "210 Elm St",
      city: "Austin",
      state: "TX",
      zipCode: "73301",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "r3",
    createdBy: "u11",
    type: "retailer",
    companyName: "Valley Supermarket",
    dbaName: "Valley Foods",
    accountId: "ACC-R003",
    phone: "(800) 555-0203",
    email: "manager@valleyfoods.com",
    fein: "96-7654323",
    resaleNumber: "RN-1234569",
    tobaccoLicense: "TL-1122336",
    idNumber: "ID-333446",
    address: {
      street: "300 Valley Hwy",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85001",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "r4",
    createdBy: "u12",
    type: "retailer",
    companyName: "QuickStop Convenience",
    dbaName: "QuickStop",
    accountId: "ACC-R004",
    phone: "(800) 555-0204",
    email: "store@quickstop.com",
    fein: "95-7654324",
    resaleNumber: "RN-1234570",
    tobaccoLicense: "TL-1122337",
    idNumber: "ID-333447",
    address: {
      street: "400 Oak Ave",
      city: "Orlando",
      state: "FL",
      zipCode: "32801",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "r5",
    createdBy: "u13",
    type: "retailer",
    companyName: "Metro Grocers",
    dbaName: "Metro Market",
    accountId: "ACC-R005",
    phone: "(800) 555-0205",
    email: "contact@metromarket.com",
    fein: "94-7654325",
    resaleNumber: "RN-1234571",
    tobaccoLicense: "TL-1122338",
    idNumber: "ID-333448",
    address: {
      street: "500 Subway Ln",
      city: "New York",
      state: "NY",
      zipCode: "10012",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "r6",
    createdBy: "u14",
    type: "retailer",
    companyName: "Sunshine Pharmacy",
    dbaName: "Sunshine Rx",
    accountId: "ACC-R006",
    phone: "(800) 555-0206",
    email: "pharmacist@sunshinerx.com",
    fein: "93-7654326",
    resaleNumber: "RN-1234572",
    tobaccoLicense: "TL-1122339",
    idNumber: "ID-333449",
    address: {
      street: "600 Solar Blvd",
      city: "San Diego",
      state: "CA",
      zipCode: "92101",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "r7",
    createdBy: "u15",
    type: "retailer",
    companyName: "Daily Fresh Needs",
    dbaName: "Fresh Foods",
    accountId: "ACC-R007",
    phone: "(800) 555-0207",
    email: "sales@freshfoods.com",
    fein: "92-7654327",
    resaleNumber: "RN-1234573",
    tobaccoLicense: "TL-1122340",
    idNumber: "ID-333450",
    address: {
      street: "700 River Rd",
      city: "Portland",
      state: "OR",
      zipCode: "97201",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "r8",
    createdBy: "u16",
    type: "retailer",
    companyName: "Urban Express",
    dbaName: "UE Kiosk",
    accountId: "ACC-R008",
    phone: "(800) 555-0208",
    email: "help@urbanexpress.com",
    fein: "91-7654328",
    resaleNumber: "RN-1234574",
    tobaccoLicense: "TL-1122341",
    idNumber: "ID-333451",
    address: {
      street: "800 Concrete St",
      city: "Atlanta",
      state: "GA",
      zipCode: "30303",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },

  // ==========================================
  // ACTIVE RESTAURANTS (8 items)
  // ==========================================
  {
    id: "rt1",
    createdBy: "u17",
    type: "restaurant",
    companyName: "Fine Dining Co.",
    dbaName: "The Fancy Fork",
    accountId: "ACC-D001",
    phone: "(800) 555-0301",
    email: "hello@fancyfork.com",
    fein: "45-6789012",
    resaleNumber: "RN-4561239",
    tobaccoLicense: "",
    idNumber: "ID-555666",
    address: {
      street: "300 Gourmet Ave",
      city: "New York",
      state: "NY",
      zipCode: "10001",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "rt2",
    createdBy: "u18",
    type: "restaurant",
    companyName: "Burger Haven",
    dbaName: "Big Buns",
    accountId: "ACC-D002",
    phone: "(800) 555-0302",
    email: "orders@burgerhaven.com",
    fein: "44-6789013",
    resaleNumber: "RN-4561240",
    tobaccoLicense: "",
    idNumber: "ID-555667",
    address: {
      street: "310 Grill Rd",
      city: "Houston",
      state: "TX",
      zipCode: "77001",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "rt3",
    createdBy: "u19",
    type: "restaurant",
    companyName: "Pasta Palace",
    dbaName: "Luigi's",
    accountId: "ACC-D003",
    phone: "(800) 555-0303",
    email: "contact@pastapalace.com",
    fein: "43-6789014",
    resaleNumber: "RN-4561241",
    tobaccoLicense: "TL-999001",
    idNumber: "ID-555668",
    address: {
      street: "320 Little Italy",
      city: "Boston",
      state: "MA",
      zipCode: "02109",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "rt4",
    createdBy: "u20",
    type: "restaurant",
    companyName: "Taco Fiesta",
    dbaName: "Fiesta Tacos",
    accountId: "ACC-D004",
    phone: "(800) 555-0304",
    email: "hola@tacofiesta.com",
    fein: "42-6789015",
    resaleNumber: "RN-4561242",
    tobaccoLicense: "",
    idNumber: "ID-555669",
    address: {
      street: "330 Spice Blvd",
      city: "San Antonio",
      state: "TX",
      zipCode: "78201",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "rt5",
    createdBy: "u21",
    type: "restaurant",
    companyName: "Green Bowl Inc",
    dbaName: "Salad Station",
    accountId: "ACC-D005",
    phone: "(800) 555-0305",
    email: "fresh@greenbowl.com",
    fein: "41-6789016",
    resaleNumber: "RN-4561243",
    tobaccoLicense: "",
    idNumber: "ID-555670",
    address: {
      street: "340 Veggie Way",
      city: "Boulder",
      state: "CO",
      zipCode: "80302",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "rt6",
    createdBy: "u22",
    type: "restaurant",
    companyName: "Morning Bean Roasters",
    dbaName: "Morning Coffee",
    accountId: "ACC-D006",
    phone: "(800) 555-0306",
    email: "brew@morningbean.com",
    fein: "40-6789017",
    resaleNumber: "RN-4561244",
    tobaccoLicense: "",
    idNumber: "ID-555671",
    address: {
      street: "350 Espresso Ln",
      city: "Seattle",
      state: "WA",
      zipCode: "98104",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "rt7",
    createdBy: "u23",
    type: "restaurant",
    companyName: "Ocean Catch Seafood",
    dbaName: "Captain's Plate",
    accountId: "ACC-D007",
    phone: "(800) 555-0307",
    email: "fish@oceancatch.com",
    fein: "39-6789018",
    resaleNumber: "RN-4561245",
    tobaccoLicense: "",
    idNumber: "ID-555672",
    address: {
      street: "360 Pier 39",
      city: "San Francisco",
      state: "CA",
      zipCode: "94133",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "rt8",
    createdBy: "u24",
    type: "restaurant",
    companyName: "Steakhouse Prime",
    dbaName: "Prime Cut",
    accountId: "ACC-D008",
    phone: "(800) 555-0308",
    email: "book@primecut.com",
    fein: "38-6789019",
    resaleNumber: "RN-4561246",
    tobaccoLicense: "TL-999002",
    idNumber: "ID-555673",
    address: {
      street: "370 Wagyu Blvd",
      city: "Las Vegas",
      state: "NV",
      zipCode: "89109",
    },
    isActive: true,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },

  // ==========================================
  // INACTIVE STORES (8 items)
  // ==========================================
  {
    id: "i1",
    createdBy: "u25",
    type: "wholesaler",
    companyName: "Inactive Wholesale Inc.",
    dbaName: "Old Market",
    accountId: "ACC-I001",
    phone: "(800) 555-0401",
    email: "closed@oldmarket.com",
    fein: "22-3344556",
    resaleNumber: "RN-5555555",
    tobaccoLicense: "TL-6666666",
    idNumber: "ID-777888",
    address: {
      street: "400 Abandoned Rd",
      city: "Detroit",
      state: "MI",
      zipCode: "48201",
    },
    isActive: false,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "i2",
    createdBy: "u26",
    type: "restaurant",
    companyName: "Closed Cafe",
    dbaName: "Moments Cafe",
    accountId: "ACC-I002",
    phone: "(800) 555-0402",
    email: "nomore@momentscafe.com",
    fein: "88-9900112",
    resaleNumber: "RN-1122334",
    tobaccoLicense: "",
    idNumber: "ID-999000",
    address: {
      street: "125 Quiet Ln",
      city: "Austin",
      state: "TX",
      zipCode: "73301",
    },
    isActive: false,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "i3",
    createdBy: "u27",
    type: "retailer",
    companyName: "Sunset Grocery",
    dbaName: "Sunset Groceries",
    accountId: "ACC-I003",
    phone: "(800) 555-0403",
    email: "bye@sunsetgrocery.com",
    fein: "77-9900113",
    resaleNumber: "RN-1122335",
    tobaccoLicense: "TL-7777777",
    idNumber: "ID-999001",
    address: {
      street: "126 Sun Ave",
      city: "Miami",
      state: "FL",
      zipCode: "33109",
    },
    isActive: false,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "i4",
    createdBy: "u28",
    type: "restaurant",
    companyName: "Frozen Treats",
    dbaName: "Ice Cream World",
    accountId: "ACC-I004",
    phone: "(800) 555-0404",
    email: "melted@frozentreats.com",
    fein: "66-9900114",
    resaleNumber: "RN-1122336",
    tobaccoLicense: "",
    idNumber: "ID-999002",
    address: {
      street: "127 Winter St",
      city: "Minneapolis",
      state: "MN",
      zipCode: "55401",
    },
    isActive: false,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "i5",
    createdBy: "u29",
    type: "wholesaler",
    companyName: "Bulk Buy Liquidators",
    dbaName: "Bulk Buy",
    accountId: "ACC-I005",
    phone: "(800) 555-0405",
    email: "liquidation@bulkbuy.com",
    fein: "55-9900115",
    resaleNumber: "RN-1122337",
    tobaccoLicense: "TL-8888888",
    idNumber: "ID-999003",
    address: {
      street: "128 Warehouse Row",
      city: "Cleveland",
      state: "OH",
      zipCode: "44113",
    },
    isActive: false,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "i6",
    createdBy: "u30",
    type: "retailer",
    companyName: "Corner Electronics",
    dbaName: "Tech Corner",
    accountId: "ACC-I006",
    phone: "(800) 555-0406",
    email: "dead@techcorner.com",
    fein: "44-9900116",
    resaleNumber: "RN-1122338",
    tobaccoLicense: "",
    idNumber: "ID-999004",
    address: {
      street: "129 Silicon Way",
      city: "San Jose",
      state: "CA",
      zipCode: "95112",
    },
    isActive: false,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "i7",
    createdBy: "u31",
    type: "restaurant",
    companyName: "Pizza Route",
    dbaName: "Route 66 Pizza",
    accountId: "ACC-I007",
    phone: "(800) 555-0407",
    email: "burnt@pizzaroute.com",
    fein: "33-9900117",
    resaleNumber: "RN-1122339",
    tobaccoLicense: "",
    idNumber: "ID-999005",
    address: {
      street: "130 Highway Rd",
      city: "Albuquerque",
      state: "NM",
      zipCode: "87102",
    },
    isActive: false,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "i8",
    createdBy: "u32",
    type: "wholesaler",
    companyName: "National Logistics",
    dbaName: "NL Distro",
    accountId: "ACC-I008",
    phone: "(800) 555-0408",
    email: "bankrupt@nldistro.com",
    fein: "22-9900118",
    resaleNumber: "RN-1122340",
    tobaccoLicense: "TL-9999999",
    idNumber: "ID-999006",
    address: {
      street: "131 Depot St",
      city: "Memphis",
      state: "TN",
      zipCode: "38103",
    },
    isActive: false,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
  },
];
