import { Notification } from "../_types/notification.types";

export const MOCK_NOTIFICATIONS: Notification[] = [
  // Critical / Security
  {
    id: "n-001",
    type: "security",
    priority: "critical",
    title: "Suspicious Login Attempt",
    message:
      "A login attempt was made from an unrecognized device (IP: 192.168.45.12, Bangladesh). If this wasn't you, secure your account immediately.",
    time: "2 min ago",
    timestamp: new Date(Date.now() - 2 * 60 * 1000),
    read: false,
    pinned: true,
    actionUrl: "/settings#security",
    actionLabel: "Secure Account",
    iconColor: "text-red-500 dark:text-red-400",
    bgColor: "bg-red-500/10 dark:bg-red-500/20",
    borderColor: "border-red-500/20",
  },
  {
    id: "n-002",
    type: "alerts",
    priority: "high",
    title: "Server Performance Alert",
    message:
      "API response time exceeded 3s threshold. Avg response: 3.7s. 12% of requests affected in the last 30 minutes.",
    time: "8 min ago",
    timestamp: new Date(Date.now() - 8 * 60 * 1000),
    read: false,
    actionUrl: "/",
    actionLabel: "View Metrics",
    iconColor: "text-orange-500 dark:text-orange-400",
    bgColor: "bg-orange-500/10 dark:bg-orange-500/20",
    borderColor: "border-orange-500/20",
  },
  // Orders
  {
    id: "n-003",
    type: "orders",
    priority: "high",
    title: "New Bulk Order Placed",
    message:
      'Wholesaler "Dhaka Fresh Mart" placed a bulk order #ORD-8821 worth ৳48,500. Requires admin approval.',
    time: "15 min ago",
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    read: false,
    actionLabel: "Review Order",
    metadata: { orderId: "ORD-8821", amount: 48500 },
    iconColor: "text-emerald-500 dark:text-emerald-400",
    bgColor: "bg-emerald-500/10 dark:bg-emerald-500/20",
    borderColor: "border-emerald-500/20",
  },
  {
    id: "n-004",
    type: "orders",
    priority: "medium",
    title: "Order Dispute Filed",
    message:
      'Retailer "City Grocery BD" filed a dispute for Order #ORD-7734. Reason: Item quantity mismatch.',
    time: "1 hour ago",
    timestamp: new Date(Date.now() - 60 * 60 * 1000),
    read: false,
    actionLabel: "Resolve Dispute",
    metadata: { orderId: "ORD-7734" },
    iconColor: "text-yellow-500 dark:text-yellow-400",
    bgColor: "bg-yellow-500/10 dark:bg-yellow-500/20",
    borderColor: "border-yellow-500/20",
  },
  {
    id: "n-005",
    type: "orders",
    priority: "low",
    title: "Order #ORD-8800 Delivered",
    message:
      'Order #ORD-8800 for "Meena Bazar" has been successfully delivered. Customer confirmed receipt.',
    time: "3 hours ago",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    read: true,
    iconColor: "text-blue-500 dark:text-blue-400",
    bgColor: "bg-blue-500/10 dark:bg-blue-500/20",
    borderColor: "border-blue-500/20",
  },
  // Connect
  {
    id: "n-006",
    type: "connect",
    priority: "medium",
    title: "New Store Registration Request",
    message:
      '"Tasty Restaurant BD" has submitted a new restaurant registration application. Documents are ready for review.',
    time: "2 hours ago",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    read: false,
    actionLabel: "Review Application",
    metadata: { userName: "Tasty Restaurant BD" },
    iconColor: "text-purple-500 dark:text-purple-400",
    bgColor: "bg-purple-500/10 dark:bg-purple-500/20",
    borderColor: "border-purple-500/20",
  },
  {
    id: "n-007",
    type: "connect",
    priority: "low",
    title: "New User Joined Platform",
    message:
      "Md. Karim Hassan registered as a new consumer on the platform. Verification pending.",
    time: "5 hours ago",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    read: true,
    metadata: { userName: "Md. Karim Hassan" },
    iconColor: "text-indigo-500 dark:text-indigo-400",
    bgColor: "bg-indigo-500/10 dark:bg-indigo-500/20",
    borderColor: "border-indigo-500/20",
  },
  // Payment
  {
    id: "n-008",
    type: "payment",
    priority: "high",
    title: "Withdrawal Request Pending",
    message:
      '"Agora Supershop" requested a withdrawal of ৳1,25,000. Requires super-admin approval before processing.',
    time: "4 hours ago",
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    read: false,
    actionLabel: "Approve Withdrawal",
    metadata: { amount: 125000, userName: "Agora Supershop" },
    iconColor: "text-cyan-500 dark:text-cyan-400",
    bgColor: "bg-cyan-500/10 dark:bg-cyan-500/20",
    borderColor: "border-cyan-500/20",
  },
  {
    id: "n-009",
    type: "payment",
    priority: "medium",
    title: "Payment Gateway Error",
    message:
      "3 transactions failed due to gateway timeout (bKash). Total affected amount: ৳12,400. Auto-retry in 10 minutes.",
    time: "6 hours ago",
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
    read: true,
    iconColor: "text-rose-500 dark:text-rose-400",
    bgColor: "bg-rose-500/10 dark:bg-rose-500/20",
    borderColor: "border-rose-500/20",
  },
  // Review
  {
    id: "n-010",
    type: "review",
    priority: "low",
    title: "New Product Review Flagged",
    message:
      'A review for "Fresh Hilsa Fish - 1kg" was flagged as inappropriate by the AI content filter. Manual review required.',
    time: "8 hours ago",
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
    read: true,
    actionLabel: "Review Content",
    iconColor: "text-amber-500 dark:text-amber-400",
    bgColor: "bg-amber-500/10 dark:bg-amber-500/20",
    borderColor: "border-amber-500/20",
  },
  // Messages
  {
    id: "n-011",
    type: "messages",
    priority: "medium",
    title: "Support Ticket Escalated",
    message:
      'Support ticket #TKT-2241 from "Noor Enterprise" has been escalated to admin. Issue: Unable to download invoice.',
    time: "1 day ago",
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    read: true,
    actionLabel: "View Ticket",
    iconColor: "text-pink-500 dark:text-pink-400",
    bgColor: "bg-pink-500/10 dark:bg-pink-500/20",
    borderColor: "border-pink-500/20",
  },
  {
    id: "n-012",
    type: "messages",
    priority: "low",
    title: "New Contact Form Submission",
    message:
      "Fatema Khanam submitted a contact request via website. Subject: Partnership Inquiry.",
    time: "1 day ago",
    timestamp: new Date(Date.now() - 26 * 60 * 60 * 1000),
    read: true,
    iconColor: "text-violet-500 dark:text-violet-400",
    bgColor: "bg-violet-500/10 dark:bg-violet-500/20",
    borderColor: "border-violet-500/20",
  },
  // Promotions
  {
    id: "n-013",
    type: "promotions",
    priority: "medium",
    title: "Promotion Campaign Ended",
    message:
      "Ramadan Special campaign has ended. Total revenue generated: ৳3,45,000. 1,246 orders were placed.",
    time: "2 days ago",
    timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000),
    read: true,
    actionLabel: "View Report",
    iconColor: "text-teal-500 dark:text-teal-400",
    bgColor: "bg-teal-500/10 dark:bg-teal-500/20",
    borderColor: "border-teal-500/20",
  },
  {
    id: "n-014",
    type: "promotions",
    priority: "low",
    title: "New Blog Published",
    message:
      'Article "Top 10 Wholesale Tips for Retailers" was published by Content Team and is now live.',
    time: "2 days ago",
    timestamp: new Date(Date.now() - 50 * 60 * 60 * 1000),
    read: true,
    iconColor: "text-lime-500 dark:text-lime-400",
    bgColor: "bg-lime-500/10 dark:bg-lime-500/20",
    borderColor: "border-lime-500/20",
  },
  // System Updates
  {
    id: "n-015",
    type: "updates",
    priority: "medium",
    title: "System Maintenance Scheduled",
    message:
      "Scheduled maintenance on April 20, 2026 from 2:00 AM - 4:00 AM (BST). All services will be unavailable.",
    time: "3 days ago",
    timestamp: new Date(Date.now() - 72 * 60 * 60 * 1000),
    read: true,
    actionLabel: "View Details",
    iconColor: "text-sky-500 dark:text-sky-400",
    bgColor: "bg-sky-500/10 dark:bg-sky-500/20",
    borderColor: "border-sky-500/20",
  },
  {
    id: "n-016",
    type: "updates",
    priority: "low",
    title: "Platform Update v3.2.1",
    message:
      "New features deployed: Advanced analytics dashboard, bulk product import/export, enhanced role management.",
    time: "5 days ago",
    timestamp: new Date(Date.now() - 120 * 60 * 60 * 1000),
    read: true,
    iconColor: "text-fuchsia-500 dark:text-fuchsia-400",
    bgColor: "bg-fuchsia-500/10 dark:bg-fuchsia-500/20",
    borderColor: "border-fuchsia-500/20",
  },
];
