// src/config/admin-menu.ts

import { AdminMenuItem } from "../../access-control/_types/access.types";
import { PERMISSIONS } from "../../access-control/_config/permission";

export const ADMIN_MENU: AdminMenuItem[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    type: "item",
    icon: "LayoutDashboard",
    path: "/admin/dashboard",
    requiredPermissions: [PERMISSIONS.DASHBOARD_VIEW],
    order: 1,
  },

  {
    id: "department",
    title: "Department",
    type: "group",
    icon: "Building2",
    requiredPermissions: [
      PERMISSIONS.DEPARTMENT_LIST,
      PERMISSIONS.DEPARTMENT_CREATE,
    ],
    order: 2,
    children: [
      {
        id: "department-add",
        title: "Add Department",
        type: "item",
        path: "/admin/department/add",
        requiredPermissions: [PERMISSIONS.DEPARTMENT_CREATE],
        order: 1,
      },
      {
        id: "department-list",
        title: "All Department",
        type: "item",
        path: "/admin/department",
        requiredPermissions: [PERMISSIONS.DEPARTMENT_LIST],
        order: 2,
      },
    ],
  },

  {
    id: "product",
    title: "Product",
    type: "group",
    icon: "Package",
    requiredPermissions: [
      PERMISSIONS.PRODUCT_LIST,
      PERMISSIONS.PRODUCT_CREATE,
      PERMISSIONS.PRODUCT_EXPIRATION_LIST,
      PERMISSIONS.PRODUCT_SELLER_LIST,
    ],
    order: 3,
    children: [
      {
        id: "product-add",
        title: "Add Product",
        type: "item",
        path: "/admin/product/add",
        requiredPermissions: [PERMISSIONS.PRODUCT_CREATE],
      },
      {
        id: "product-manage",
        title: "Manage Product",
        type: "item",
        path: "/admin/product/manage",
        requiredPermissions: [PERMISSIONS.PRODUCT_LIST],
      },
      {
        id: "product-expiration",
        title: "Expiration Product",
        type: "item",
        path: "/admin/product/expiration",
        requiredPermissions: [PERMISSIONS.PRODUCT_EXPIRATION_LIST],
      },
      {
        id: "product-sellers",
        title: "Sellers Product",
        type: "item",
        path: "/admin/product/sellers",
        requiredPermissions: [PERMISSIONS.PRODUCT_SELLER_LIST],
      },
    ],
  },

  {
    id: "user",
    title: "User",
    type: "group",
    icon: "Users",
    requiredPermissions: [
      PERMISSIONS.USER_REQUEST_LIST,
      PERMISSIONS.USER_REQUEST_CREATE,
      PERMISSIONS.WHOLESALER_LIST,
      PERMISSIONS.RETAILER_LIST,
      PERMISSIONS.RESTAURANT_LIST,
      PERMISSIONS.CONSUMER_LIST,
      PERMISSIONS.LOGIN_HISTORY_LIST,
      PERMISSIONS.INACTIVE_ACCOUNT_LIST,
    ],
    order: 4,
    children: [
      {
        id: "user-new-request",
        title: "New Request",
        type: "item",
        path: "/admin/user/new-request",
        requiredPermissions: [PERMISSIONS.USER_REQUEST_CREATE],
      },
      {
        id: "user-wholesaler",
        title: "Wholesaler",
        type: "item",
        path: "/admin/user/wholesaler",
        requiredPermissions: [PERMISSIONS.WHOLESALER_LIST],
      },
      {
        id: "user-retailer",
        title: "Retailer",
        type: "item",
        path: "/admin/user/retailer",
        requiredPermissions: [PERMISSIONS.RETAILER_LIST],
      },
      {
        id: "user-restaurant",
        title: "Restaurant",
        type: "item",
        path: "/admin/user/restaurant",
        requiredPermissions: [PERMISSIONS.RESTAURANT_LIST],
      },
      {
        id: "user-consumer",
        title: "Consumer",
        type: "item",
        path: "/admin/user/consumer",
        requiredPermissions: [PERMISSIONS.CONSUMER_LIST],
      },
      {
        id: "user-login",
        title: "Login",
        type: "item",
        path: "/admin/user/login",
        requiredPermissions: [PERMISSIONS.LOGIN_HISTORY_LIST],
      },
      {
        id: "user-inactive",
        title: "Inactive Account",
        type: "item",
        path: "/admin/user/inactive-account",
        requiredPermissions: [PERMISSIONS.INACTIVE_ACCOUNT_LIST],
      },
    ],
  },

  {
    id: "connect",
    title: "Connect",
    type: "group",
    icon: "Link2",
    requiredPermissions: [
      PERMISSIONS.CONNECT_REQUEST_LIST,
      PERMISSIONS.CONNECT_REQUEST_CREATE,
      PERMISSIONS.CONNECTED_ACCOUNT_LIST,
    ],
    order: 5,
    children: [
      {
        id: "connect-new-request",
        title: "New Request",
        type: "item",
        path: "/admin/connect/new-request",
        requiredPermissions: [PERMISSIONS.CONNECT_REQUEST_CREATE],
      },
      {
        id: "connect-connected",
        title: "Connected",
        type: "item",
        path: "/admin/connect/connected",
        requiredPermissions: [PERMISSIONS.CONNECTED_ACCOUNT_LIST],
      },
    ],
  },

  {
    id: "order",
    title: "Order",
    type: "group",
    icon: "ShoppingCart",
    requiredPermissions: [PERMISSIONS.ORDER_LIST],
    order: 6,
    children: [
      {
        id: "order-manage",
        title: "Manage Order",
        type: "item",
        path: "/admin/order/manage",
        requiredPermissions: [PERMISSIONS.ORDER_LIST],
      },
    ],
  },

  {
    id: "report",
    title: "Report",
    type: "group",
    icon: "FileText",
    requiredPermissions: [PERMISSIONS.REPORT_LIST, PERMISSIONS.ETIMESHEET_LIST],
    order: 7,
    children: [
      {
        id: "report-manage",
        title: "Manage Report",
        type: "item",
        path: "/admin/report/manage",
        requiredPermissions: [PERMISSIONS.REPORT_LIST],
      },
      {
        id: "report-etimesheet",
        title: "E-Timesheet",
        type: "item",
        path: "/admin/report/e-timesheet",
        requiredPermissions: [PERMISSIONS.ETIMESHEET_LIST],
      },
    ],
  },

  {
    id: "stock",
    title: "Stock",
    type: "group",
    icon: "Boxes",
    requiredPermissions: [PERMISSIONS.STOCK_LIST],
    order: 8,
    children: [
      {
        id: "stock-manage",
        title: "Manage Stock",
        type: "item",
        path: "/admin/stock/manage",
        requiredPermissions: [PERMISSIONS.STOCK_LIST],
      },
    ],
  },

  {
    id: "account",
    title: "Account",
    type: "group",
    icon: "Wallet",
    requiredPermissions: [
      PERMISSIONS.WHOLESALER_DUE_LIST,
      PERMISSIONS.RETAILER_DUE_LIST,
      PERMISSIONS.INVOICE_REPORT_LIST,
      PERMISSIONS.PAYINOUT_REPORT_LIST,
      PERMISSIONS.EPAY_REPORT_LIST,
      PERMISSIONS.WITHDRAW_REPORT_LIST,
      PERMISSIONS.BILLING_VIEW,
    ],
    order: 9,
    children: [
      {
        id: "account-wholesaler-due",
        title: "Wholesaler Due",
        type: "item",
        path: "/admin/account/wholesaler-due",
        requiredPermissions: [PERMISSIONS.WHOLESALER_DUE_LIST],
      },
      {
        id: "account-retailer-due",
        title: "Retailer Due",
        type: "item",
        path: "/admin/account/retailer-due",
        requiredPermissions: [PERMISSIONS.RETAILER_DUE_LIST],
      },
      {
        id: "account-invoice-report",
        title: "Invoice Report",
        type: "item",
        path: "/admin/account/invoice-report",
        requiredPermissions: [PERMISSIONS.INVOICE_REPORT_LIST],
      },
      {
        id: "account-payinout-report",
        title: "Pay-In/Out Report",
        type: "item",
        path: "/admin/account/pay-in-out-report",
        requiredPermissions: [PERMISSIONS.PAYINOUT_REPORT_LIST],
      },
      {
        id: "account-epay-report",
        title: "E.pay Report",
        type: "item",
        path: "/admin/account/e-pay-report",
        requiredPermissions: [PERMISSIONS.EPAY_REPORT_LIST],
      },
      {
        id: "account-withdraw-report",
        title: "Withdraw Report",
        type: "item",
        path: "/admin/account/withdraw-report",
        requiredPermissions: [PERMISSIONS.WITHDRAW_REPORT_LIST],
      },
      {
        id: "account-billing-manage",
        title: "Billing Manage",
        type: "item",
        path: "/admin/account/billing-manage",
        requiredPermissions: [PERMISSIONS.BILLING_VIEW],
      },
    ],
  },

  {
    id: "setting",
    title: "Setting",
    type: "group",
    icon: "Settings",
    requiredPermissions: [
      PERMISSIONS.CONTACT_REQUEST_LIST,
      PERMISSIONS.WEB_SUBSCRIBER_LIST,
      PERMISSIONS.VERIFICATION_LIST,
    ],
    order: 10,
    children: [
      {
        id: "setting-contacted-by-web",
        title: "Contacted By Web",
        type: "item",
        path: "/admin/setting/contacted-by-web",
        requiredPermissions: [PERMISSIONS.CONTACT_REQUEST_LIST],
      },
      {
        id: "setting-web-subscribe",
        title: "Web Subscribe",
        type: "item",
        path: "/admin/setting/web-subscribe",
        requiredPermissions: [PERMISSIONS.WEB_SUBSCRIBER_LIST],
      },
      {
        id: "setting-verification",
        title: "Verification",
        type: "item",
        path: "/admin/setting/verification",
        requiredPermissions: [PERMISSIONS.VERIFICATION_LIST],
      },
    ],
  },

  {
    id: "promotion",
    title: "Promotion",
    type: "group",
    icon: "Megaphone",
    requiredPermissions: [
      PERMISSIONS.PROMOTION_LIST,
      PERMISSIONS.PROMOTION_CREATE,
    ],
    order: 11,
    children: [
      {
        id: "promotion-manage",
        title: "Promotion",
        type: "item",
        path: "/admin/promotion",
        requiredPermissions: [PERMISSIONS.PROMOTION_LIST],
      },
      {
        id: "promotion-add",
        title: "Add Promotion",
        type: "item",
        path: "/admin/promotion/add",
        requiredPermissions: [PERMISSIONS.PROMOTION_CREATE],
      },
    ],
  },

  {
    id: "role",
    title: "Role",
    type: "group",
    icon: "ShieldCheck",
    requiredPermissions: [PERMISSIONS.ROLE_LIST, PERMISSIONS.ROLE_CREATE],
    order: 12,
    children: [
      {
        id: "role-manage",
        title: "Manage Role",
        type: "item",
        path: "/admin/role/manage",
        requiredPermissions: [PERMISSIONS.ROLE_LIST],
      },
      {
        id: "role-add",
        title: "Add Role",
        type: "item",
        path: "/admin/role/add",
        requiredPermissions: [PERMISSIONS.ROLE_CREATE],
      },
    ],
  },

  {
    id: "store-hub",
    title: "Store Hub",
    type: "group",
    icon: "Store",
    requiredPermissions: [
      PERMISSIONS.STORE_HUB_RETAILER_LIST,
      PERMISSIONS.STORE_HUB_WHOLESALER_LIST,
      PERMISSIONS.STORE_OWNER_CREATE,
    ],
    order: 13,
    children: [
      {
        id: "store-hub-retailer",
        title: "Retailer",
        type: "item",
        path: "/admin/store-hub/retailer",
        requiredPermissions: [PERMISSIONS.STORE_HUB_RETAILER_LIST],
      },
      {
        id: "store-hub-wholesaler",
        title: "Wholesaler",
        type: "item",
        path: "/admin/store-hub/wholesaler",
        requiredPermissions: [PERMISSIONS.STORE_HUB_WHOLESALER_LIST],
      },
      {
        id: "store-hub-add-owner",
        title: "Add Owner",
        type: "item",
        path: "/admin/store-hub/add-owner",
        requiredPermissions: [PERMISSIONS.STORE_OWNER_CREATE],
      },
    ],
  },

  {
    id: "support-hub",
    title: "Support Hub",
    type: "group",
    icon: "Headphones",
    requiredPermissions: [
      PERMISSIONS.SUPPORT_RESOURCE_LIST,
      PERMISSIONS.SUPPORT_ARTICLE_LIST,
      PERMISSIONS.SUPPORT_CHATBOT_MANAGE,
      PERMISSIONS.SUPPORT_LEARNING_VIDEO_LIST,
    ],
    order: 14,
    children: [
      {
        id: "support-resource",
        title: "Resource",
        type: "item",
        path: "/admin/support/resource",
        requiredPermissions: [PERMISSIONS.SUPPORT_RESOURCE_LIST],
      },
      {
        id: "support-article",
        title: "Article",
        type: "item",
        path: "/admin/support/article",
        requiredPermissions: [PERMISSIONS.SUPPORT_ARTICLE_LIST],
      },
      {
        id: "support-chatbot",
        title: "Chatbot",
        type: "item",
        path: "/admin/support/chatbot",
        requiredPermissions: [PERMISSIONS.SUPPORT_CHATBOT_MANAGE],
      },
      {
        id: "support-learning-video",
        title: "Learning Video",
        type: "item",
        path: "/admin/support/learning-video",
        requiredPermissions: [PERMISSIONS.SUPPORT_LEARNING_VIDEO_LIST],
      },
    ],
  },

  {
    id: "blog",
    title: "Blog",
    type: "group",
    icon: "NotebookPen",
    requiredPermissions: [
      PERMISSIONS.BLOG_CATEGORY_LIST,
      PERMISSIONS.BLOG_LIST,
      PERMISSIONS.BLOG_CREATE,
    ],
    order: 15,
    children: [
      {
        id: "blog-category",
        title: "Blog Category",
        type: "item",
        path: "/admin/blog/category",
        requiredPermissions: [PERMISSIONS.BLOG_CATEGORY_LIST],
      },
      {
        id: "blog-add",
        title: "Add Blog",
        type: "item",
        path: "/admin/blog/add",
        requiredPermissions: [PERMISSIONS.BLOG_CREATE],
      },
      {
        id: "blog-manage",
        title: "Manage Blog",
        type: "item",
        path: "/admin/blog/manage",
        requiredPermissions: [PERMISSIONS.BLOG_LIST],
      },
    ],
  },

  {
    id: "hiring",
    title: "Hiring Deck",
    type: "group",
    icon: "BriefcaseBusiness",
    requiredPermissions: [
      PERMISSIONS.JOB_CATEGORY_LIST,
      PERMISSIONS.SERVICE_CATEGORY_LIST,
      PERMISSIONS.HIRING_LIST,
      PERMISSIONS.HIRING_CREATE,
    ],
    order: 16,
    children: [
      {
        id: "hiring-job-category",
        title: "Job Category",
        type: "item",
        path: "/admin/hiring/job-category",
        requiredPermissions: [PERMISSIONS.JOB_CATEGORY_LIST],
      },
      {
        id: "hiring-service-category",
        title: "Service Category",
        type: "item",
        path: "/admin/hiring/service-category",
        requiredPermissions: [PERMISSIONS.SERVICE_CATEGORY_LIST],
      },
      {
        id: "hiring-add",
        title: "Add Hiring",
        type: "item",
        path: "/admin/hiring/add",
        requiredPermissions: [PERMISSIONS.HIRING_CREATE],
      },
      {
        id: "hiring-manage",
        title: "Manage Hiring",
        type: "item",
        path: "/admin/hiring/manage",
        requiredPermissions: [PERMISSIONS.HIRING_LIST],
      },
    ],
  },

  {
    id: "help-center",
    title: "Help Center",
    type: "item",
    icon: "BadgeHelp",
    path: "/admin/help-center",
    requiredPermissions: [PERMISSIONS.HELP_CENTER_VIEW],
    order: 17,
  },
];
