import { BlogCategory, BlogPost } from "../_types/blog.types";

export const MOCK_BLOG_CATEGORIES: BlogCategory[] = [
  {
    id: "cat_1",
    name: "Technology",
    slug: "technology",
    postCount: 15,
    status: "active",
    createdAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "cat_2",
    name: "Business",
    slug: "business",
    postCount: 8,
    status: "active",
    createdAt: "2024-03-02T10:00:00Z",
  },
  {
    id: "cat_3",
    name: "Marketing",
    slug: "marketing",
    postCount: 5,
    status: "inactive",
    createdAt: "2024-03-03T10:00:00Z",
  },
  {
    id: "cat_4",
    name: "Design",
    slug: "design",
    postCount: 12,
    status: "active",
    createdAt: "2024-03-04T10:00:00Z",
  },
  {
    id: "cat_1",
    name: "Technology",
    slug: "technology",
    postCount: 15,
    status: "active",
    createdAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "cat_2",
    name: "Business",
    slug: "business",
    postCount: 8,
    status: "active",
    createdAt: "2024-03-02T10:00:00Z",
  },
  {
    id: "cat_3",
    name: "Marketing",
    slug: "marketing",
    postCount: 5,
    status: "inactive",
    createdAt: "2024-03-03T10:00:00Z",
  },
  {
    id: "cat_4",
    name: "Design",
    slug: "design",
    postCount: 12,
    status: "active",
    createdAt: "2024-03-04T10:00:00Z",
  },
];

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: "post_1",
    title: "The Future of Web Development",
    slug: "future-of-web-development",
    categoryId: "cat_1",
    bannerImage: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
    altText: "Laptop on desk",
    imageTitle: "Web Development",
    metaTitle: "The Future of Web Development in 2026",
    metaDescription: "Exploring the upcoming trends in web development...",
    content:
      "<p>This is a mock blog post content covering the future of web dev.</p>",
    status: "published",
    views: 1250,
    createdAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "post_2",
    title: "10 Marketing Strategies for Startups",
    slug: "10-marketing-strategies",
    categoryId: "cat_3",
    bannerImage: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0",
    altText: "Marketing team meeting",
    imageTitle: "Marketing Strategies",
    metaTitle: "10 Best Marketing Strategies for Beginners",
    metaDescription: "Learn how to market your new startup efficiently.",
    content: "<p>Startups need robust marketing strategies. Here are 10...</p>",
    status: "draft",
    views: 0,
    createdAt: "2024-03-12T14:00:00Z",
  },
  {
    id: "post_3",
    title: "Effective Supply Chain Management",
    slug: "supply-chain-management",
    categoryId: "cat_2",
    bannerImage: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
    altText: "Warehouse operations",
    imageTitle: "Supply Chain",
    metaTitle: "How to optimize your supply chain",
    metaDescription: "A practical guide to supply chain opimization.",
    content: "<p>Managing supply chains is critical. Here is how...</p>",
    status: "published",
    views: 342,
    createdAt: "2024-03-15T09:30:00Z",
  },
];
