import {
  HiringCategory,
  HiringPost,
  JobApplication,
} from "../_types/hiring.types";

// ─── Categories ───────────────────────────────────────────────────────────────
export const MOCK_HIRING_CATEGORIES: HiringCategory[] = [
  {
    id: "hcat_1",
    name: "Software Engineering",
    slug: "software-engineering",
    type: "job",
    postCount: 24,
    status: "active",
    createdAt: "2025-01-10T10:00:00Z",
  },
  {
    id: "hcat_2",
    name: "Product Design",
    slug: "product-design",
    type: "job",
    postCount: 12,
    status: "active",
    createdAt: "2025-01-12T10:00:00Z",
  },
  {
    id: "hcat_3",
    name: "Marketing & Growth",
    slug: "marketing-growth",
    type: "job",
    postCount: 8,
    status: "active",
    createdAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "hcat_4",
    name: "Operations & Logistics",
    slug: "operations-logistics",
    type: "job",
    postCount: 5,
    status: "inactive",
    createdAt: "2025-02-01T10:00:00Z",
  },
  {
    id: "hcat_5",
    name: "Delivery & Transport",
    slug: "delivery-transport",
    type: "service",
    postCount: 18,
    status: "active",
    createdAt: "2025-02-10T10:00:00Z",
  },
  {
    id: "hcat_6",
    name: "Cleaning & Maintenance",
    slug: "cleaning-maintenance",
    type: "service",
    postCount: 9,
    status: "active",
    createdAt: "2025-02-15T10:00:00Z",
  },
  {
    id: "hcat_7",
    name: "Catering & Food Service",
    slug: "catering-food",
    type: "service",
    postCount: 4,
    status: "inactive",
    createdAt: "2025-03-01T10:00:00Z",
  },
];

// ─── Hiring Posts ─────────────────────────────────────────────────────────────
export const MOCK_HIRING_POSTS: HiringPost[] = [
  {
    id: "hire_1",
    title: "Senior Full-Stack Developer",
    companyName: "TechVentures Ltd.",
    companyLogo:
      "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=80&h=80&fit=crop",
    bannerImage:
      "https://images.unsplash.com/photo-1573495628136-22e97736b365?w=800&h=400&fit=crop",
    categoryId: "hcat_1",
    address: "123 Tech Park, Gulshan-2",
    city: "Dhaka",
    country: "Bangladesh",
    jobType: "full-time",
    salaryMin: 80000,
    salaryMax: 130000,
    salaryType: "monthly",
    currency: "BDT",
    description:
      "<p>We are looking for an experienced Full-Stack Developer to join our growing team. You will build scalable web apps using React and Node.js.</p>",
    requirements:
      "<ul><li>5+ years of experience with React & Node.js</li><li>Proficiency in TypeScript</li><li>Experience with PostgreSQL or MongoDB</li><li>Strong understanding of REST APIs</li></ul>",
    benefits:
      "<ul><li>Competitive salary</li><li>Annual bonus</li><li>Remote work flexibility</li><li>Health insurance</li></ul>",
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL"],
    experience: "5+ years",
    education: "Bachelor's in CSE or equivalent",
    openings: 2,
    deadline: "2026-05-01T00:00:00Z",
    status: "active",
    views: 1240,
    applicationCount: 38,
    createdAt: "2026-03-15T10:00:00Z",
    updatedAt: "2026-03-20T10:00:00Z",
  },
  {
    id: "hire_2",
    title: "UI/UX Product Designer",
    companyName: "PixelCraft Studio",
    companyLogo:
      "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=80&h=80&fit=crop",
    bannerImage:
      "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=400&fit=crop",
    categoryId: "hcat_2",
    address: "45 Creative Lane, Dhanmondi",
    city: "Dhaka",
    country: "Bangladesh",
    jobType: "full-time",
    salaryMin: 60000,
    salaryMax: 90000,
    salaryType: "monthly",
    currency: "BDT",
    description:
      "<p>Join our design team to craft beautiful, user-centric interfaces for our suite of products.</p>",
    requirements:
      "<ul><li>3+ years in UI/UX design</li><li>Proficient in Figma & Adobe Creative Suite</li><li>Portfolio showcasing past work</li></ul>",
    benefits:
      "<ul><li>Creative work environment</li><li>Flexible schedule</li><li>Professional development budget</li></ul>",
    skills: ["Figma", "Adobe XD", "Prototyping", "User Research"],
    experience: "3-5 years",
    education: "Bachelor's in Design or Fine Arts",
    openings: 1,
    deadline: "2026-04-30T00:00:00Z",
    status: "active",
    views: 890,
    applicationCount: 21,
    createdAt: "2026-03-18T10:00:00Z",
    updatedAt: "2026-03-25T10:00:00Z",
  },
  {
    id: "hire_3",
    title: "Digital Marketing Specialist",
    companyName: "GrowthBox Agency",
    bannerImage:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=400&fit=crop",
    categoryId: "hcat_3",
    address: "78 Commerce Road, Motijheel",
    city: "Dhaka",
    country: "Bangladesh",
    jobType: "full-time",
    salaryMin: 45000,
    salaryMax: 65000,
    salaryType: "monthly",
    currency: "BDT",
    description:
      "<p>We're seeking a passionate Digital Marketing Specialist to drive our client campaigns across all channels.</p>",
    requirements:
      "<ul><li>2+ years in digital marketing</li><li>Experience with Google Ads & Meta Ads</li><li>SEO & content strategy knowledge</li><li>Analytics and reporting skills</li></ul>",
    benefits:
      "<ul><li>Performance bonuses</li><li>Training certifications</li><li>Casual work culture</li></ul>",
    skills: ["SEO", "Google Ads", "Meta Ads", "Analytics", "Content Strategy"],
    experience: "2-4 years",
    education: "Bachelor's in Marketing or Business",
    openings: 3,
    deadline: "2026-04-20T00:00:00Z",
    status: "active",
    views: 620,
    applicationCount: 14,
    createdAt: "2026-03-20T10:00:00Z",
    updatedAt: "2026-03-22T10:00:00Z",
  },
  {
    id: "hire_4",
    title: "Professional Delivery Rider",
    companyName: "SwiftDrop Logistics",
    bannerImage:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
    categoryId: "hcat_5",
    address: "Service Area: Dhaka City",
    city: "Dhaka",
    country: "Bangladesh",
    jobType: "part-time",
    salaryMin: 15000,
    salaryMax: 25000,
    salaryType: "monthly",
    currency: "BDT",
    description:
      "<p>We need reliable delivery riders to cover our expanding service area in Dhaka. Flexible hours, bike provided.</p>",
    requirements:
      "<ul><li>Valid driving license</li><li>Own smartphone</li><li>Knowledge of Dhaka roads</li><li>Physically fit</li></ul>",
    benefits:
      "<ul><li>Flexible working hours</li><li>Fuel allowance</li><li>Performance bonuses</li><li>Insurance coverage</li></ul>",
    skills: ["Navigation", "Time Management", "Customer Service"],
    experience: "No prior experience needed",
    education: "SSC minimum",
    openings: 10,
    deadline: "2026-05-15T00:00:00Z",
    status: "active",
    views: 2100,
    applicationCount: 87,
    createdAt: "2026-03-10T10:00:00Z",
    updatedAt: "2026-03-12T10:00:00Z",
  },
  {
    id: "hire_5",
    title: "React Native Mobile Developer",
    companyName: "AppForge Technologies",
    bannerImage:
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=400&fit=crop",
    categoryId: "hcat_1",
    address: "Plot 17, BSEC Building, Agrabad",
    city: "Chittagong",
    country: "Bangladesh",
    jobType: "remote",
    salaryMin: 70000,
    salaryMax: 110000,
    salaryType: "monthly",
    currency: "BDT",
    description:
      "<p>Seeking a talented React Native developer to build and maintain world-class mobile applications for iOS and Android.</p>",
    requirements:
      "<ul><li>4+ years React Native development</li><li>Published apps on App Store or Play Store</li><li>Knowledge of native modules</li></ul>",
    benefits:
      "<ul><li>100% remote work</li><li>Competitive salary</li><li>Equipment allowance</li><li>Unlimited PTO</li></ul>",
    skills: ["React Native", "iOS", "Android", "Redux", "REST APIs"],
    experience: "4+ years",
    education: "BSc in Computer Science or equivalent",
    openings: 2,
    deadline: "2026-05-30T00:00:00Z",
    status: "draft",
    views: 0,
    applicationCount: 0,
    createdAt: "2026-04-01T10:00:00Z",
    updatedAt: "2026-04-01T10:00:00Z",
  },
  {
    id: "hire_6",
    title: "Office Cleaning Services Contract",
    companyName: "CleanPro Solutions",
    bannerImage:
      "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&h=400&fit=crop",
    categoryId: "hcat_6",
    address: "Multiple Locations, Dhaka",
    city: "Dhaka",
    country: "Bangladesh",
    jobType: "contract",
    salaryMin: 12000,
    salaryMax: 18000,
    salaryType: "monthly",
    currency: "BDT",
    description:
      "<p>We provide reliable office cleaning services and are looking for dedicated cleaning staff for corporate clients.</p>",
    requirements:
      "<ul><li>Experience in commercial cleaning</li><li>Attention to detail</li><li>Ability to work early hours</li></ul>",
    benefits:
      "<ul><li>Stable contract</li><li>Uniform provided</li><li>End-of-year bonus</li></ul>",
    skills: ["Cleaning", "Reliability", "Punctuality"],
    experience: "1+ year preferred",
    education: "No formal education required",
    openings: 5,
    status: "closed",
    views: 430,
    applicationCount: 19,
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-02-20T10:00:00Z",
  },
];

// ─── Job Applications ─────────────────────────────────────────────────────────
export const MOCK_JOB_APPLICATIONS: JobApplication[] = [
  {
    id: "app_1",
    hiringId: "hire_1",
    hiringTitle: "Senior Full-Stack Developer",
    companyName: "TechVentures Ltd.",
    applicantName: "Rafiq Hossain",
    applicantEmail: "rafiq.hossain@email.com",
    applicantPhone: "+880 1712-345678",
    applicantLocation: "Dhaka, Bangladesh",
    applicantPhoto:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face",
    coverLetter:
      "Dear Hiring Manager, I am a passionate full-stack developer with 6 years of experience. I have successfully led multiple teams and delivered production-grade applications...",
    resumeUrl: "https://example.com/resume/rafiq.pdf",
    portfolioUrl: "https://rafiq.dev",
    linkedInUrl: "https://linkedin.com/in/rafiq",
    expectedSalary: 120000,
    availableFrom: "2026-05-01T00:00:00Z",
    status: "shortlisted",
    appliedAt: "2026-03-22T09:15:00Z",
    updatedAt: "2026-03-25T14:30:00Z",
  },
  {
    id: "app_2",
    hiringId: "hire_1",
    hiringTitle: "Senior Full-Stack Developer",
    companyName: "TechVentures Ltd.",
    applicantName: "Sarah Johnson",
    applicantEmail: "sarah.johnson@example.com",
    applicantPhone: "+1 555-234-5678",
    applicantLocation: "Remote (USA)",
    coverLetter:
      "Hello, I am a senior developer based in the US looking for remote opportunities. I specialize in React and microservices architecture...",
    resumeUrl: "https://example.com/resume/sarah.pdf",
    linkedInUrl: "https://linkedin.com/in/sarahj",
    expectedSalary: 100000,
    availableFrom: "2026-06-01T00:00:00Z",
    status: "pending",
    appliedAt: "2026-03-23T11:00:00Z",
    updatedAt: "2026-03-23T11:00:00Z",
  },
  {
    id: "app_3",
    hiringId: "hire_2",
    hiringTitle: "UI/UX Product Designer",
    companyName: "PixelCraft Studio",
    applicantName: "Minhaj Rahman",
    applicantEmail: "minhaj.r@design.bd",
    applicantPhone: "+880 1812-987654",
    applicantLocation: "Dhaka, Bangladesh",
    applicantPhoto:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face",
    coverLetter:
      "I am a creative designer with 4 years of experience crafting user-centric digital experiences. My portfolio includes work for leading Bangladeshi startups...",
    resumeUrl: "https://example.com/resume/minhaj.pdf",
    portfolioUrl: "https://minhaj.design",
    expectedSalary: 75000,
    availableFrom: "2026-04-20T00:00:00Z",
    status: "reviewed",
    appliedAt: "2026-03-25T08:30:00Z",
    updatedAt: "2026-03-28T10:00:00Z",
  },
  {
    id: "app_4",
    hiringId: "hire_2",
    hiringTitle: "UI/UX Product Designer",
    companyName: "PixelCraft Studio",
    applicantName: "Priya Patel",
    applicantEmail: "priya.patel@creative.in",
    applicantPhone: "+91 99009 12345",
    applicantLocation: "Mumbai, India",
    coverLetter:
      "Enthusiastic designer with expertise in Figma and user research. I believe design should solve real problems...",
    portfolioUrl: "https://priyapatel.co",
    expectedSalary: 70000,
    status: "rejected",
    appliedAt: "2026-03-26T14:00:00Z",
    updatedAt: "2026-03-30T09:00:00Z",
  },
  {
    id: "app_5",
    hiringId: "hire_3",
    hiringTitle: "Digital Marketing Specialist",
    companyName: "GrowthBox Agency",
    applicantName: "Tanvir Ahmed",
    applicantEmail: "tanvir.mkt@gmail.com",
    applicantPhone: "+880 1912-456789",
    applicantLocation: "Chittagong, Bangladesh",
    coverLetter:
      "I have 3 years of hands-on experience with Google Ads and social media campaigns. I managed a ৳50 Lac monthly ad budget for an e-commerce brand...",
    resumeUrl: "https://example.com/resume/tanvir.pdf",
    expectedSalary: 55000,
    availableFrom: "2026-05-10T00:00:00Z",
    status: "hired",
    appliedAt: "2026-03-21T10:00:00Z",
    updatedAt: "2026-04-01T16:00:00Z",
  },
  {
    id: "app_6",
    hiringId: "hire_4",
    hiringTitle: "Professional Delivery Rider",
    companyName: "SwiftDrop Logistics",
    applicantName: "Alam Mia",
    applicantEmail: "alam.mia@yahoo.com",
    applicantPhone: "+880 1523-789012",
    applicantLocation: "Mirpur, Dhaka",
    coverLetter:
      "I am interested in the delivery rider position. I have a valid driving license and good knowledge of Dhaka roads...",
    status: "pending",
    appliedAt: "2026-03-28T07:00:00Z",
    updatedAt: "2026-03-28T07:00:00Z",
  },
  {
    id: "app_7",
    hiringId: "hire_1",
    hiringTitle: "Senior Full-Stack Developer",
    companyName: "TechVentures Ltd.",
    applicantName: "Chen Wei",
    applicantEmail: "chen.wei@techjobs.cn",
    applicantPhone: "+86 138 0000 5678",
    applicantLocation: "Shanghai, China (Remote)",
    coverLetter:
      "Experienced full-stack engineer from Shanghai, open to remote positions. Proficient in MERN stack with 7 years of experience...",
    resumeUrl: "https://example.com/resume/chenwei.pdf",
    portfolioUrl: "https://github.com/chenwei",
    expectedSalary: 110000,
    availableFrom: "2026-05-01T00:00:00Z",
    status: "shortlisted",
    appliedAt: "2026-03-24T05:30:00Z",
    updatedAt: "2026-03-27T11:00:00Z",
  },
];
