import { PERMISSIONS } from "@/components/modules/access-control/_config/permission";
import { Role } from "../_types/role.types";

export const MOCK_ROLES: Role[] = [
  {
    id: "role-super-admin",
    name: "Super Admin",
    description: "Full access to all modules and settings across the platform.",
    status: "active",
    isSystem: true,
    userCount: 2,
    assignedUserIds: ["user-008", "user-009"],
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
    permissions: Object.values(PERMISSIONS).map((key) => ({
      key,
      scope: "global" as const,
    })),
  },
  {
    id: "role-manager",
    name: "Manager",
    description:
      "Can manage users, orders, reports and most operational tasks.",
    status: "active",
    isSystem: false,
    userCount: 8,
    assignedUserIds: ["user-001", "user-003", "user-006", "user-007"],
    createdAt: "2025-02-15T00:00:00Z",
    updatedAt: "2026-02-20T00:00:00Z",
    permissions: [
      { key: PERMISSIONS.DASHBOARD_VIEW, scope: "global" },
      { key: PERMISSIONS.USER_REQUEST_LIST, scope: "global" },
      { key: PERMISSIONS.WHOLESALER_LIST, scope: "global" },
      { key: PERMISSIONS.RETAILER_LIST, scope: "global" },
      { key: PERMISSIONS.RESTAURANT_LIST, scope: "global" },
      { key: PERMISSIONS.CONSUMER_LIST, scope: "global" },
      { key: PERMISSIONS.ORDER_LIST, scope: "global" },
      { key: PERMISSIONS.ORDER_UPDATE, scope: "global" },
      { key: PERMISSIONS.REPORT_LIST, scope: "global" },
      { key: PERMISSIONS.STOCK_LIST, scope: "global" },
      { key: PERMISSIONS.INVOICE_REPORT_LIST, scope: "global" },
      { key: PERMISSIONS.PRODUCT_LIST, scope: "global" },
    ],
  },
  {
    id: "role-moderator",
    name: "Moderator",
    description: "Handles content moderation, blogs, support and promotions.",
    status: "active",
    isSystem: false,
    userCount: 5,
    assignedUserIds: ["user-004", "user-010"],
    createdAt: "2025-03-10T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
    permissions: [
      { key: PERMISSIONS.DASHBOARD_VIEW, scope: "global" },
      { key: PERMISSIONS.BLOG_LIST, scope: "global" },
      { key: PERMISSIONS.BLOG_CREATE, scope: "global" },
      { key: PERMISSIONS.BLOG_CATEGORY_LIST, scope: "global" },
      { key: PERMISSIONS.PROMOTION_LIST, scope: "global" },
      { key: PERMISSIONS.PROMOTION_CREATE, scope: "global" },
      { key: PERMISSIONS.SUPPORT_ARTICLE_LIST, scope: "global" },
      { key: PERMISSIONS.SUPPORT_RESOURCE_LIST, scope: "global" },
      { key: PERMISSIONS.SUPPORT_CHATBOT_MANAGE, scope: "global" },
    ],
  },
  {
    id: "role-accountant",
    name: "Accountant",
    description: "Access to all financial reports, billing and accounts.",
    status: "active",
    isSystem: false,
    userCount: 3,
    assignedUserIds: ["user-002", "user-005"],
    createdAt: "2025-04-01T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
    permissions: [
      { key: PERMISSIONS.DASHBOARD_VIEW, scope: "global" },
      { key: PERMISSIONS.WHOLESALER_DUE_LIST, scope: "global" },
      { key: PERMISSIONS.RETAILER_DUE_LIST, scope: "global" },
      { key: PERMISSIONS.INVOICE_REPORT_LIST, scope: "global" },
      { key: PERMISSIONS.PAYINOUT_REPORT_LIST, scope: "global" },
      { key: PERMISSIONS.EPAY_REPORT_LIST, scope: "global" },
      { key: PERMISSIONS.WITHDRAW_REPORT_LIST, scope: "global" },
      { key: PERMISSIONS.BILLING_VIEW, scope: "global" },
      { key: PERMISSIONS.REPORT_LIST, scope: "global" },
    ],
  },
  {
    id: "role-viewer",
    name: "Viewer",
    description: "Read-only access to dashboard and reports only.",
    status: "draft",
    isSystem: false,
    userCount: 0,
    assignedUserIds: [],
    createdAt: "2026-03-20T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
    permissions: [
      { key: PERMISSIONS.DASHBOARD_VIEW, scope: "global" },
      { key: PERMISSIONS.REPORT_LIST, scope: "global" },
    ],
  },
];
